import { toast } from "sonner";

const baseStyles = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Georgia', serif;
    line-height: 1.8;
    color: #1a1a1a;
    padding: 40px;
    max-width: 800px;
    margin: 0 auto;
  }
  .header {
    text-align: center;
    margin-bottom: 40px;
    padding-bottom: 20px;
    border-bottom: 2px solid #e5e5e5;
  }
  .header h1 { font-size: 28px; color: #2563eb; margin-bottom: 8px; }
  .header p { color: #666; font-size: 14px; }
  .section { margin-bottom: 24px; page-break-inside: avoid; }
  .question { 
    background: #f8fafc; 
    border: 1px solid #e2e8f0; 
    border-radius: 8px; 
    padding: 16px; 
    margin-bottom: 16px;
  }
  .question-text { font-weight: 600; color: #1e293b; margin-bottom: 12px; }
  .question-number { color: #2563eb; }
  .answer { 
    background: #f0f9ff; 
    border-left: 4px solid #2563eb; 
    padding: 12px; 
    border-radius: 0 8px 8px 0;
  }
  .answer-label { font-weight: 600; color: #2563eb; font-size: 14px; margin-bottom: 4px; }
  .option { 
    display: flex; 
    align-items: center; 
    gap: 12px; 
    padding: 8px 12px; 
    margin: 4px 0; 
    border-radius: 6px;
    background: #fff;
    border: 1px solid #e2e8f0;
  }
  .option.correct { background: #f0fdf4; border-color: #bbf7d0; }
  .option-letter {
    width: 28px;
    height: 28px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 600;
    font-size: 14px;
  }
  .option.correct .option-letter { background: #22c55e; color: white; }
  .option:not(.correct) .option-letter { background: #f1f5f9; color: #64748b; }
  .point {
    display: flex;
    gap: 12px;
    padding: 12px;
    background: #f8fafc;
    border-radius: 8px;
    margin-bottom: 8px;
  }
  .point-icon { color: #22c55e; font-size: 18px; }
  .summary-box {
    background: linear-gradient(135deg, #eff6ff, #f0f9ff);
    border: 1px solid #bfdbfe;
    border-radius: 12px;
    padding: 24px;
  }
  .footer {
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid #e5e5e5;
    text-align: center;
    color: #888;
    font-size: 12px;
  }
  @media print { body { padding: 20px; } .section { page-break-inside: avoid; } }
`;

const createPrintWindow = (title: string, content: string) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    toast.error("Please allow popups to export PDF");
    return null;
  }

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>${baseStyles}</style>
    </head>
    <body>
      <div class="header">
        <h1>📚 ${title}</h1>
        <p>Generated on ${new Date().toLocaleDateString()}</p>
      </div>
      ${content}
      <div class="footer">
        <p>Generated by StudyBuddy AI</p>
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
  printWindow.onload = () => printWindow.print();
  toast.success("Print dialog opened - Save as PDF!");
  return printWindow;
};

export const exportSummary = (summary: string) => {
  const content = `
    <div class="summary-box">
      <p style="font-size: 16px; line-height: 1.8;">${summary}</p>
    </div>
  `;
  createPrintWindow("Study Summary", content);
};

export const exportImportantPoints = (points: string[]) => {
  const content = points.map((point, i) => `
    <div class="point">
      <span class="point-icon">✓</span>
      <p>${point}</p>
    </div>
  `).join('');
  createPrintWindow("Important Points", content);
};

export const exportMCQs = (mcqs: { question: string; options: string[]; correctAnswer: number }[]) => {
  const content = mcqs.map((mcq, i) => `
    <div class="question">
      <p class="question-text">
        <span class="question-number">Q${i + 1}.</span> ${mcq.question}
      </p>
      <div>
        ${mcq.options.map((opt, j) => `
          <div class="option ${j === mcq.correctAnswer ? 'correct' : ''}">
            <span class="option-letter">${String.fromCharCode(65 + j)}</span>
            <span>${opt}</span>
            ${j === mcq.correctAnswer ? '<span style="margin-left:auto;color:#22c55e;">✓</span>' : ''}
          </div>
        `).join('')}
      </div>
    </div>
  `).join('');
  createPrintWindow("MCQs with Answers", content);
};

export const exportShortQuestions = (questions: { question: string; answer: string }[]) => {
  const content = questions.map((q, i) => `
    <div class="question">
      <p class="question-text">
        <span class="question-number">Q${i + 1}.</span> ${q.question}
      </p>
      <div class="answer">
        <p class="answer-label">Answer:</p>
        <p>${q.answer}</p>
      </div>
    </div>
  `).join('');
  createPrintWindow("Short Questions & Answers", content);
};

export const exportLongQuestions = (questions: { question: string; answer: string }[]) => {
  const content = questions.map((q, i) => `
    <div class="question" style="page-break-inside: avoid;">
      <p class="question-text">
        <span class="question-number">Question ${i + 1}:</span> ${q.question}
      </p>
      <div class="answer" style="margin-top: 12px;">
        <p class="answer-label">Detailed Answer:</p>
        <p style="white-space: pre-wrap;">${q.answer}</p>
      </div>
    </div>
  `).join('');
  createPrintWindow("Long Questions & Answers", content);
};

export const exportVivaQuestions = (questions: { question: string; answer: string }[]) => {
  const content = questions.map((q, i) => `
    <div class="question">
      <p class="question-text">
        <span class="question-number">V${i + 1}.</span> ${q.question}
      </p>
      <div class="answer">
        <p class="answer-label">Answer:</p>
        <p>${q.answer}</p>
      </div>
    </div>
  `).join('');
  createPrintWindow("Viva Questions & Answers", content);
};

export const exportDetailedNotes = (notes: { heading: string; content: string; keyPoints?: string[] }[]) => {
  const content = notes.map((note, i) => `
    <div class="section" style="margin-bottom: 32px;">
      <h2 style="font-size: 20px; color: #1e40af; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 1px solid #dbeafe; display: flex; align-items: center; gap: 12px;">
        <span style="background: #2563eb; color: white; width: 28px; height: 28px; border-radius: 6px; display: inline-flex; align-items: center; justify-content: center; font-size: 14px;">${i + 1}</span>
        ${note.heading}
      </h2>
      <p style="text-align: justify; margin-bottom: 16px; color: #333;">${note.content}</p>
      ${note.keyPoints && note.keyPoints.length > 0 ? `
        <div style="background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 16px; margin-top: 12px;">
          <p style="font-weight: bold; color: #15803d; margin-bottom: 8px; font-size: 14px;">💡 Key Takeaways</p>
          <ul style="list-style: none; padding-left: 0;">
            ${note.keyPoints.map(point => `<li style="padding: 4px 0; padding-left: 20px; position: relative; font-size: 14px;"><span style="position: absolute; left: 0; color: #22c55e;">✓</span>${point}</li>`).join('')}
          </ul>
        </div>
      ` : ''}
    </div>
  `).join('');
  createPrintWindow("Detailed Study Notes", content);
};
